AWSTemplateFormatVersion: "2010-09-09"
Description:  KMS Key to be used to automatically unseal vault

Resources:
  Key:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: An example symmetric KMS key
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${AWS::AccountId}:user/Oscar'
                - !Sub 'arn:aws:iam::${AWS::AccountId}:user/george'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::143441593752:role/New-IAM-Management-SSMIAMRole-1KXYG8T09P7QM'
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'
      Tags:
      - Key: Name
        Value: Vault-AutoUnseal-Key

  KeyAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: alias/Core
      TargetKeyId: !Ref Key
           

Outputs:
  KeyArn:
    Value: !GetAtt Key.Arn
    Export: 
      Name: KeyArn