version: 0.2

phases:
  install: 
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Installing dependancies...
      - chmod +x gradlew

  build: 
    commands:
      - echo Building Api Service
      - ./gradlew clean spotlessApply build -x test

Artifacts:
  files:
    - build/libs/*    
    - appspec.yml
    - pipeline-files/*
  discard-paths: yes     

cache:
  paths:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
