AWSTemplateFormatVersion: "2010-09-09"
Description: Ajua Bastion launch template and auto-scaling group

Parameters:
  # EnvironmentType:
  #   Description: 'Specify the Environment type of the stack.'
  #   Type: String
  #   Default: Test
  #   AllowedValues:
  #     - Test
  #     - Prod
  #   ConstraintDescription: 'Specify either Test or Prod.'

  AmiID:
    Type: AWS::EC2::Image::Id
    Description: 'The ID of the AMI.' # uses the latest ami id  
    Default: 'ami-00e7df8df28dfa791' #ami-00e7df8df28dfa791

  EC2InstanceType:
    Type: String
    Description: Provide the desired instance type
    Default: t3.nano 

  KeyName: 
    Type: String
    Default: core-platform-key
    Description: Enter a key pair name of the key you'll use to ssh  

  Subnet1:  
    Type: AWS::EC2::Subnet::Id
    Description: 'The Subnet ID'
  Subnet2:  
    Type: AWS::EC2::Subnet::Id
    Description: 'The Subnet ID' 

  SgId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Enter a valid security group ID

  # TargetGroupARNs:
  #   Type: String #should be list
  #   Default: arn:aws:elasticloadbalancing:us-east-2:071046007207:targetgroup/TargetGroup1/4911679704360b5e #get from elb stack output

  OperatorEMail:
    Description: EMail address to notify if there are any scaling operations
    Type: String
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: must be a valid email address.  
    Default: testsoscar@gmail.com

  CPUPolicyTargetValue:
    Type: String
    Default: '80'

Resources:
  NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        Subscription:
        - Endpoint: !Ref 'OperatorEMail'
          Protocol: email

  BastionLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: Bastion-Launch-Template
      LaunchTemplateData:
        InstanceType: !Ref EC2InstanceType
        ImageId: 
          Ref: AmiID
        SecurityGroupIds: #add sg heres
          - Ref: SgId
        IamInstanceProfile: 
          Name: !ImportValue SSMInstanceProfile
        KeyName: !Ref KeyName 
        # BlockDeviceMappings:
        #   - Ebs:
        #       VolumeSize: 15 # put a desired volume
        #       VolumeType: gp3
        #       DeleteOnTermination: true
        #     DeviceName: /dev/xvdcz  
        UserData: #add user data here 
          Fn::Base64: |
            #!/bin/bash
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            # install updates
            # yum update -y #for centos
            sudo apt update -y
            
            # configure AWS CLI for ec2-user / ubuntu
            mkdir ~/.aws
            cat > ~/.aws/config<< EOF
            [default]
            region = ${AWS::Region}
            EOF

  BastionASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: BastionASG
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"       
      HealthCheckGracePeriod: 60
      LaunchTemplate:
        LaunchTemplateId: 
          Ref: BastionLaunchTemplate
        Version: !GetAtt BastionLaunchTemplate.LatestVersionNumber
      NewInstancesProtectedFromScaleIn: false  
      VPCZoneIdentifier:
        - Ref: Subnet1
        - Ref: Subnet2
      # TargetGroupARNs: 
      #   - !Ref TargetGroupARNs
      Tags:
      -   Key: Name
          PropagateAtLaunch: true
          Value: Bastion-Host  
      NotificationConfigurations:
        - TopicARN: !Ref 'NotificationTopic'
          NotificationTypes: ['autoscaling:EC2_INSTANCE_LAUNCH', 'autoscaling:EC2_INSTANCE_LAUNCH_ERROR',
            'autoscaling:EC2_INSTANCE_TERMINATE', 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR']
      
  # BastionScalingPolicy:
  #   Type: AWS::AutoScaling::ScalingPolicy
  #   Properties:
  #     AutoScalingGroupName: !Ref BastionASG
  #     PolicyType: TargetTrackingScaling
  #     TargetTrackingConfiguration: 
  #       PredefinedMetricSpecification:
  #         PredefinedMetricType: ASGAverageCPUUtilization
  #       TargetValue: !Ref CPUPolicyTargetValue


# Outputs: 
  